apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-guard.fastapiService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "fastapi") | nindent 4 }}
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "fastapi") | nindent 4 }}
