apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-guard.grafanaService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "grafana") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "grafana") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fraud-guard.labels" . | nindent 8 }}
        {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "grafana") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.auth.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fraud-guard.fullname" . }}-secret
                  key: GF_SECURITY_ADMIN_PASSWORD
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-data
              mountPath: /var/lib/grafana
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: datasources
          configMap:
            name: {{ include "fraud-guard.grafanaService" . }}-datasources
        - name: dashboard-provider
          configMap:
            name: {{ include "fraud-guard.grafanaService" . }}-dashboard-provider
        - name: dashboards
          configMap:
            name: {{ include "fraud-guard.grafanaService" . }}-dashboards
        - name: grafana-data
          emptyDir: {}
