apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-guard.kafkaService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "kafka") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: 9092
      protocol: TCP
      name: broker
    - port: 29093
      targetPort: 29093
      protocol: TCP
      name: controller
  selector:
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "kafka") | nindent 4 }}
