apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fraud-guard.postgresService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  serviceName: {{ include "fraud-guard.postgresService" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fraud-guard.labels" . | nindent 8 }}
        {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "postgres") | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "fraud-guard.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "-E UTF8"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-schema
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}
                - -d
                - {{ .Values.postgres.auth.database }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.auth.username }}
                - -d
                - {{ .Values.postgres.auth.database }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: init-schema
          configMap:
            name: {{ include "fraud-guard.fullname" . }}-schema
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgres.storage.storageClass }}
        storageClassName: {{ .Values.postgres.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
