apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fraud-guard.prometheusService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "prometheus") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "prometheus") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fraud-guard.labels" . | nindent 8 }}
        {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "prometheus") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=7d'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fraud-guard.prometheusService" . }}-config
        - name: data
          emptyDir: {}
