apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-guard.prometheusService" . }}-config
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'fraud-detection-api'
        static_configs:
          - targets: ['{{ include "fraud-guard.fastapiService" . }}:{{ .Values.fastapi.service.port }}']
        metrics_path: '/metrics'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
