apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fraud-guard.fullname" . }}-secret
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.auth.adminPassword | b64enc | quote }}
