apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-guard.sparkMasterService" . }}
  labels:
    {{- include "fraud-guard.labels" . | nindent 4 }}
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "spark-master") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.spark.master.service.port }}
      targetPort: 7077
      protocol: TCP
      name: master
    - port: {{ .Values.spark.master.service.webPort }}
      targetPort: 8080
      protocol: TCP
      name: web-ui
  selector:
    {{- include "fraud-guard.selectorLabels" (dict "context" . "component" "spark-master") | nindent 4 }}
