apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: fraud_detection
    user: frauduser
    secureJsonData:
      password: fraudpass123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    editable: true
